nome01 = input("digite seu nome")
nome02 = input("digite seu nome")
nome03 = input("digite seu nome")
print("boa noite " + nome01)
print("boa noite " + nome02)
print("boa noite " + nome03)
print("boa noite " + nome01, nome02,nome03)